# 1. استخدم Java
FROM eclipse-temurin:17-jdk-alpine

# 2. فولدر الشغل جوه الكونتينر
WORKDIR /app

# 3. انسخ ملفات Maven
COPY pom.xml .
COPY mvnw .
COPY .mvn .mvn

# 4. نزّل dependencies
RUN ./mvnw dependency:go-offline

# 5. انسخ باقي المشروع
COPY src src

# 6. build
RUN ./mvnw clean package -DskipTests

# 7. شغّل التطبيق
CMD ["java", "-jar", "target/storely-0.0.1-SNAPSHOT.jar"]
