spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${SUPABASE_URL}:6543/postgres?sslmode=require&prepareThreshold=0
    username: ${SUPABASE_USERNAME}
    password: ${SUPABASE_PASSWORD}

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

logging:
  level:
    org.hibernate.engine.jdbc.env.internal: debug
    org.springframework.jdbc.datasource: debug
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace


cloudflare:
  r2:
    bucket: ${CLOUDFLARE_R2_BUCKET}
    public-url: ${CLOUDFLARE_R2_PUBLIC_URL}
    access-key: ${CLOUDFLARE_R2_ACCESS_KEY}
    secret-key: ${CLOUDFLARE_R2_SECRET_KEY}
    account-id: ${CLOUDFLARE_R2_ACCOUNT_ID}

token:
  secret: hjfs46687kjsfkj@#@$#$@$%ffeddf@#sADDS
  time: 36000000